apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: sxd-platform
    provider: github
    repository: hello-world-npm
  name: sxd-platform-hello-world-npm
spec:
  description: Imported application for sxd-platform/hello-world-npm
  httpCloneURL: https://github.com/sxd-platform/hello-world-npm
  org: sxd-platform
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: hello-world-npm
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/sxd-platform/hello-world-npm
